# Generated by Django 5.2 on 2025-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=40)),
                ('style', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=20)),
                ('occasion', models.CharField(max_length=20)),
                ('outfit', models.ManyToManyField(to='main_app.outfit')),
            ],
        ),
    ]
